export const courses = [
  'Nenhum',
  'Administração',
  'Agronomia',
  'Análise e Desenvolvimento de Sistemas',
  'Arquitetura de interiores',
  'Arquitetura e Urbanismo',
  'Arquivologia',
  'Artes Cênicas',
  'Biblioteconomia',
  'Biomedicina',
  'Ciência da Computação',
  'Ciências Biológicas',
  'Ciências Contábeis',
  'Ciências Econômicas',
  'Ciências Sociais',
  'Ciência de Dados',
  'Ciências do Esporte',
  'Ciências Ambientais',
  'Ciência Política',
  'Comunicação Social (Jornalismo)',
  'Comunicação Social (Relações Públicas)',
  'Design Gráfico',
  'Design de Interiores',
  'Design de Moda',
  'Direito',
  'Educação Artística',
  'Educação Física',
  'Enfermagem',
  'Engenharia Aeroespacial',
  'Engenharia Civil',
  'Engenharia Elétrica',
  'Engenharia Ambiental',
  'Engenharia de Materiais',
  'Engenharia de Petróleo',
  'Engenharia de Produção',
  'Engenharia de Química',
  'Engenharia Mecânica',
  'Engenharia de Software',
  'Farmácia',
  'Filosofia',
  'Fisioterapia',
  'Física',
  'Geografia',
  'Gestão de Projetos',
  'Gestão Empresarial',
  'História',
  'Letras',
  'Marketing',
  'Matemática',
  'Medicina',
  'Medicina Veterinária',
  'Nutrição',
  'Odontologia',
  'Pedagogia',
  'Psicologia',
  'Química',
  'Secretariado Executivo',
  'Serviço Social',
  'Sistemas de Informação',
  'Terapia da Fala e Linguagem',
  'Terapia Ocupacional',
  'Zootecnia',
  'Outro',
]
